# Generated by Django 2.1.7 on 2019-06-19 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 17, 20, 34, 424297)),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='ca_restaurant_list', to='restaurants.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='co_restaurant_list', to='restaurants.Comment'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, related_name='fo_restaurant_list', to='restaurants.Food'),
        ),
    ]
